# Generated by Django 5.2.6 on 2025-12-03 13:48

from django.db import migrations, models
import django.core.files.storage
import os
from django.conf import settings

def move_avatars_to_media_folder(apps, schema_editor):
    """
    Di chuyển avatar files từ folder avatars/ cũ sang media/avatars/
    """
    User = apps.get_model('users', 'User')
    old_avatar_dir = os.path.join(settings.BASE_DIR, 'avatars')
    new_avatar_dir = os.path.join(settings.MEDIA_ROOT, 'avatars')
    
    # Đảm bảo folder mới tồn tại
    os.makedirs(new_avatar_dir, exist_ok=True)
    
    for user in User.objects.all():
        if user.avatar and user.avatar.name:
            old_path = user.avatar.path
            # Kiểm tra nếu file đang ở folder cũ
            if old_path.startswith(old_avatar_dir):
                filename = os.path.basename(old_path)
                new_path = os.path.join(new_avatar_dir, filename)
                
                # Di chuyển file nếu tồn tại và chưa có ở folder mới
                if os.path.exists(old_path) and not os.path.exists(new_path):
                    import shutil
                    shutil.move(old_path, new_path)
                
                # Cập nhật đường dẫn trong database
                user.avatar.name = f'avatars/{filename}'
                user.save(update_fields=['avatar'])

def reverse_move_avatars(apps, schema_editor):
    """
    Reverse migration - di chuyển avatar về folder cũ
    """
    User = apps.get_model('users', 'User')
    old_avatar_dir = os.path.join(settings.BASE_DIR, 'avatars')
    new_avatar_dir = os.path.join(settings.MEDIA_ROOT, 'avatars')
    
    for user in User.objects.all():
        if user.avatar and user.avatar.name:
            filename = os.path.basename(user.avatar.name)
            old_path = os.path.join(new_avatar_dir, filename)
            new_path = os.path.join(old_avatar_dir, filename)
            
            if os.path.exists(old_path):
                os.makedirs(old_avatar_dir, exist_ok=True)
                import shutil
                shutil.move(old_path, new_path)
                user.avatar.name = filename
                user.save(update_fields=['avatar'])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_user_date_of_birth_user_nickname'),
    ]

    operations = [
        migrations.RunPython(move_avatars_to_media_folder, reverse_move_avatars),
    ]
