# Generated by Django 5.2.7 on 2025-12-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link video từ cloud cho phát trực tiếp', max_length=1000, null=True),
        ),
    ]
